let shopItemsData = [
    {
        id: 'hwebjwbwfenwjence',
        title: 'Casual Shirt',
        price: 25,
        desc: 'This piece was designed by Yomi casual. The award winning Fashion designer',
        imageURL: '/src/images/img-1.jpg',
    },
    {
        id: 'dcjwuiehucweiuwfwe',
        title: 'Office Shirts',
        price: 40,
        desc: 'This piece was designed by Yomi casual. The award winning Fashion designer',
        imageURL: '/src/images/img-2.jpg',
    },
    {
        id: 'kwjdiojqwodqcmjfiji',
        title: 'T-Shirt',
        price: 20,
        desc: 'This piece was designed by Yomi casual. The award winning Fashion designer',
        imageURL: '/src/images/img-3.jpg',
    },
    {
        id: 'uivheiojwicwmmcoefefewf',
        title: 'Men Suit',
        price: 80,
        desc: 'This piece was designed by Yomi casual. The award winning Fashion designer',
        imageURL: '/src/images/img-4.jpg',
    },
    {
      id: "thiecbawdjksadjk",
      title: "Mens Tie",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      imageURL: "/src/images/img-5.png",
    },
    {
      id: "iuertrywebncdjksadjk",
      title: "Casual shoes",
      price: 200,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      imageURL: "/src/images/img-6.png",
    },
    {
      id: "thierytbvcbvzdhadjk",
      title: "black suit",
      price: 450,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      imageURL: "/src/images/img-7.png",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      title: "polo shirt",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      imageURL: "/src/images/img-8.png",
    },
    {
      id: "cbvxbcvsceldk",
      title: "denim shirt",
      price: 85,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      imageURL: "/src/images/img-9.png",
    },
    {
      id: "oiopijmjkhuihb",
      title: "denim pants",
      price: 120,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      imageURL: "/src/images/img-10.png",
    },
    {
      id: "oiopijewyiohbjhib",
      title: "basic cap",
      price: 35,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      imageURL: "/src/images/img-11.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      title: "leather boots",
      price: 350,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      imageURL: "/src/images/img-12.png",
    },
]